name: Documentation Improvement
description: Suggest improvements or report issues with documentation
title: "[Docs]: "
labels: ["documentation"]
assignees:
  - assagman
body:
  - type: markdown
    attributes:
      value: |
        Help us improve the documentation!

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation type
      options:
        - README
        - Code comments
        - Wiki / external docs
        - Other
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where is the issue? (file path, section, URL)
      placeholder: "README.md, Installation section"
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: What's wrong or missing?
      description: Describe the problem with the current docs
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested improvement
      description: How should it be improved?
    validations:
      required: false
